# ALS Research Project Configuration
project:
  name: "ALS_Diagnosis_with_SHAP"
  version: "1.0.0"
  description: "Machine Learning-based ALS diagnosis with SHAP interpretability"
  random_seed: 42

# Data configuration
data:
  base_dir: "data"
  datasets: ["GSE112676", "GSE112680"]
  sample_types: ["ALS", "Control"] # Exclude ALS-mimic as per paper
  test_size: 0.1
  validation_split: 0.2

# Data preprocessing
preprocessing:
  normalization: "StandardScaler"
  remove_low_variance: true
  variance_threshold: 0.01
  handle_missing: "drop" # or "impute"
  outlier_detection: false

# Feature selection configuration
feature_selection:
  # MMPC parameters
  mmpc:
    significance_threshold: 0.1
    max_features: 24 # As per research paper

  # Ridge ranking parameters
  ridge:
    alpha_range: [0.01, 0.1, 1.0, 10.0, 100.0]
    cv_folds: 5

  # Sequential Forward Feature Selection
  sffs:
    max_features: 24
    cv_folds: 4
    scoring: "accuracy"

# Machine Learning algorithms
modeling:
  algorithms:
    - "LogisticRegression"
    - "AdaBoost"
    - "KNN"
    - "RandomForest"
    - "XGBoost"
    - "SVM"
    - "DecisionTree"

  hyperparameter_tuning: true
  cv_folds: 4
  n_jobs: -1 # Use all available cores

# SHAP configuration
shap:
  explainer_type: "auto" # auto, tree, linear, kernel
  num_background_samples: 50
  max_analysis_samples: 100
  generate_plots: true
  analyze_interactions: true
  plot_formats: ["png"]
  dpi: 300

# Logging configuration
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  save_logs: true
  log_file: "logs/pipeline.log"

# Output configuration
output:
  save_intermediate_results: true
  save_models: true
  generate_reports: true
  create_visualizations: true

# Performance settings
performance:
  n_jobs: -1 # Number of parallel jobs (-1 for all cores)
  memory_limit: "8GB" # Memory usage limit
  cache_results: true

# Reproducibility
reproducibility:
  set_random_seeds: true
  save_environment: true
  track_versions: true
